# Generated by Django 5.2.1 on 2025-05-29 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='visits.session'),
        ),
        migrations.AlterField(
            model_name='sessionentrycomment',
            name='session_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='visits.sessionentry'),
        ),
    ]
