# Generated by Django 5.2.3 on 2025-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionentry',
            old_name='check_out',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='sessionentry',
            old_name='check_in',
            new_name='start',
        ),
        migrations.AddField(
            model_name='sessionentry',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sessionentry',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('LUNCH', 'Lunch'), ('BREAK', 'Break'), ('WORK', 'Work')], default='SYSTEM', max_length=10),
        ),
        migrations.DeleteModel(
            name='SessionEntryComment',
        ),
    ]
