stages:
  - build
  - test
  - deploy

build_backend_image:
  stage: build
  before_script:
    echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:latest backend
    - docker push $CI_REGISTRY_IMAGE/backend:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
      changes:
        - backend/{,**/}*
        - .gitlab-ci.yml
  tags:
    - builder

build_backend_image_dev:
  stage: build
  before_script:
    echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t --build-arg ENVIRONMENT='dev' $CI_REGISTRY_IMAGE/backend:dev backend
    - docker push $CI_REGISTRY_IMAGE/backend:dev
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "dev"
      when: on_success
      changes:
        - backend/{,**/}*
        - .gitlab-ci.yml
  tags:
    - builder

build_mqtt_subscriber_image:
  stage: build
  before_script:
    echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE/mqtt_subscriber:latest mqtt_subscriber
    - docker push $CI_REGISTRY_IMAGE/mqtt_subscriber:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
      changes:
        - mqtt_subscriber/{,**/}*
        - .gitlab-ci.yml
  tags:
    - builder

generate_schema:
  stage: build
  image: $CI_REGISTRY_IMAGE/backend:latest
  script:
    - cd /var/www/backend
    - python manage.py spectacular --file schema.yml
    - mv schema.yml $CI_PROJECT_DIR/
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
  artifacts:
    paths:
      - schema.yml
    expire_in: 30 minutes
  needs:
    - job: build_backend_image
      artifacts: false
  tags:
    - docker-builder

build_frontend:
  stage: build
  image: node:20
  needs:
    - job: generate_schema
      artifacts: true
  script:
    - test -z "$FRONTEND_ENV_FILE" && exit 1
    - cp "$FRONTEND_ENV_FILE" frontend/.env
    - cd frontend
    - yarn install
    - SCHEMA_URL=$CI_PROJECT_DIR/schema.yml yarn api:generate
    - yarn build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
  artifacts:
    paths:
      - frontend/dist
    expire_in: 30 minutes
  tags:
    - docker-builder

test_ruff:
  stage: test
  image: $CI_REGISTRY_IMAGE/backend:dev
  script:
    - ruff check .
  tags:
    - docker-builder

deploy_app:
  stage: deploy
  script:
    - echo "Deploying app..."
    - test -z "$PROJECT_ROOT" && exit 1
    - rsync -av --delete $CI_PROJECT_DIR/nginx $PROJECT_ROOT/nginx
    - rsync -av --delete $CI_PROJECT_DIR/docker-compose.yml $PROJECT_ROOT/
    - rsync -av --delete $CI_PROJECT_ROOT/frontend/dist $PROJECT_ROOT/frontend/dist
    - cd $PROJECT_ROOT
    - docker compose pull
    - docker compose up -d
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
      changes:
        - backend/{,**/}*
        - .gitlab-ci.yml
  tags:
    - ssh-deploy

apply_migrations:
  stage: deploy
  needs:
    - job: deploy_app
  script:
    - test -z "$PROJECT_ROOT" && exit 1
    - cd $PROJECT_ROOT
    - docker compose run --rm --no-deps backend python manage.py migrate
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
      changes:
        - backend/*/migrations/
        - backend/*/migrations/*.py
        - .gitlab-ci.yml
