volumes:
  python_sock:

services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - backend/static:/var/www/backend/static:ro
      - backend/media:/var/www/backend/media:ro
      - frontend/dist:/var/www/frontend/dist:ro
      - python_sock:/var/run/python

  backend:
    restart: unless-stopped
    image: visits_django/backend
    build: backend
    volumes:
      - python_sock:/var/run/python
    env_file:
      - backend/.env


  mqtt_subscriber:
    image: visits_django/mqtt_subscriber
    build: mqtt_subscriber
    env_file:
      - mqtt_subscriber/.env