services:
  nginx:
    volumes:
      - ./nginx/conf.dev.d:/etc/nginx/conf.d:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`visits.<domain>`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    depends_on:
      - backend
      - frontend

  backend:
    image: visits_django/backend:dev
    build:
      context: backend
      args:
        PYTHON_IMAGE_VERSION: 3.14
        ENVIRONMENT: development
    command: python -m debugpy --listen 0.0.0:5678 -m uvicorn main.asgi:application --host 0.0.0.0 --port 5000
    ports:
      - 5678:5678
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "yarn install && yarn dev --host"
    environment:
      - NODE_ENV=development

  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=visits
      - MARIADB_PASSWORD=visitsPwd!
      - MARIADB_DATABASE=visits
    volumes:
      - ../dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  ldap:
    image: bitnami/openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - ../ldap:/bitnami/openldap
    ports:
      - 1389:1389
