services:
  nginx:
    volumes:
      - ./docker/nginx/conf.dev.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    image: visits_django/backend:dev
    build:
      context: docker/backend
      dockerfile: Dockerfile.dev
    ports:
      - 5678:5678
    depends_on:
      - db
      - ldap

  frontend:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      sh -c "yarn install &&
             yarn dev --host"
    environment:
      - NODE_ENV=development

  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=visits
      - MARIADB_PASSWORD=visitsPwd!
      - MARIADB_DATABASE=visits
    volumes:
      - ../dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  ldap:
    image: bitnami/openldap
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - ../ldap:/bitnami/openldap
    ports:
      - 1389:1389
