volumes:
  python_sock:
  static_dir:
  media_dir:

services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./frontend/dist:/var/www/frontend/dist:ro
      - static_dir:/var/www/static:ro
      - media_dir:/var/www/media:ro
      - python_sock:/var/run/python

  backend:
    restart: unless-stopped
    image: registry.deeplace.md/visits/visits-django/backend:latest
    build:
      context: backend
      args:
        PYTHON_IMAGE_VERSION: 3.14
        ENVIRONMENT: production
    volumes:
      - static_dir:/app/static:ro
      - media_dir:/app/media:ro
      - python_sock:/var/run/python
    env_file:
      - backend/.env

  mqtt_subscriber:
    image: registry.deeplace.md/visits/visits-django/mqtt_subscriber
    build: mqtt_subscriber
    env_file:
      - mqtt_subscriber/.env