volumes:
  python_sock:

services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - python_sock:/var/run/python
      - ./backend/static:/var/www/backend/static:ro
      - ./backend/media:/var/www/backend/media:ro

  backend:
    restart: unless-stopped
    image: visits_django/backend
    build: docker/backend
    volumes:
      - python_sock:/var/run/python
      - ./backend:/var/www/backend
    env_file:
      - ./backend/.env


  mqtt_subscriber:
    image: visits_django/mqtt_subscriber
    build: mqtt_subscriber
    environment:
      - MQTT_CLIENT
      - MQTT_TOPIC
      - MQTT_PASS
      - MQTT_LOGIN
      - MQTT_SERVER
      - MQTT_PORT
      - WEBAPP_URL
      - AUTH_TOKEN
