# Generated by Django 5.2.4 on 2025-07-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_alter_rfidsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidsettings',
            name='rfid_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
